#!/usr/bin/env zsh

set -e

PYTHON_VERSION=3.12.2

CONFIG="install.conf.yaml"
DOTBOT_DIR="deps/dotbot"
DOTBOT_BREW_DIR="deps/dotbot-brew"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" \
  --verbose \
  --plugin-dir ${DOTBOT_BREW_DIR} \
  -c "${CONFIG}" "${@}"

# install python
pyenv install "${PYTHON_VERSION}"
pyenv global "${PYTHON_VERSION}"
pyenv rehash